all:
	#/opt/matlab/bin/matlab -r 'measure_edge_effects_on_filter_perf()' -nojvm -nosplash -logfile out.log < exit_cmd.m
	#gimp filter_clustered_mle_log_intensity_single_run_scene2.eps &
	/opt/matlab/bin/matlab -r 'bdd()' -nojvm -nosplash -logfile out.log < exit_cmd.m
	gimp bdd.eps &
	#firefox bdd.svg &
